# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 518eeefa521c46ee7e03310fdd1e25838f8a742ef7db1703ffdd91e2ad6e90d1148ed0ae4d472bb86d63fcfe47763e31e6e8cf0e63287d0d3f52babffc792a0f

test:
  secret_key_base: 81c7420c8cf89ebce97c84a214505a9e2b80abe937d9bb0f479fa62767fd8cc512ea3be1f47cd88d38a97d291a692f43193fe4cbda875b042d8b8a298fc95db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
